all:	program1	program2	program3	program4
program1:	zigzagconf.c
		gcc zigzagconf.c -o zigzagconf -lm 
program2:	server.c
		gcc server.c -o mypingsrv

program3:	client.c
		gcc client.c -o mypingcli -lm
program4:
		gcc zigzagrouter.c -o zigzagrouter -lm